### PR TITLE
Update HitbtcTradeServiceRaw.java

### PR DESCRIPTION
**Pull request by cymp**
lots sizes are now dynamically retrieved from Hitbtc at trade service creation

### CODE REVIEW

**Comment by npomfret** [comment]
Are the hard coded lots now unused?

**Comment by cymp** [comment]
Wel, they should be unused now. I left them just in case the dynamic fetching of the data fails, in this case the hard coded values are here as a backup.

**Comment by npomfret** [comment]
I think they should be removed. I guarantee it will cause confusion in the future. Either your change works or it doesn't (I'm sure it does!)

**Comment by cymp** [comment]
Ok I can do that. Anyways the future of this part of the library is the new API, but no one seems to be happy to take my bounty and implement it :)

**Comment by npomfret** [comment]
I might also be able to take a look at implementing the new api - will see how much work it is first.

**Pull request closed without merging**
