### PR TITLE
changed partner to api_key

### PR DESCRIPTION
**Pull request by davassi**
'partner' key is no more longer supported by OkCoin usd

### CODE REVIEW

**Comment by jheusser** [comment]
@davassi Is this tested for okcoin.cn as well?

**Comment by zholmes1** [comment]
It should be fine. In zTrader I am using the implementation that can be seen in my pull request and I haven't had any complaints from my users on okcoin.cn. In my implementation I just changed everything to String but still sent it as "partner" and everything seems fine.

**Comment by zholmes1** [comment]
Just checked the documentation for both .cn and .com and they are both now looking for "api_key."

**Comment by davassi** [comment]
@jheusser Actually not, I did not test against .cn. But as @zholmes1 confirm, and I even asked directly to the okcoin online support, the partner key is deprecated both side. The documentation of okcoin has some typos as well...

**Comment by jheusser** [comment]
ok cool, thanks guys.

**Comment by MaximSultakov** [comment]
Is it possible to have it fixed in 2.1 which is stored in Maven Repo?

**Comment by rafalkrupinski** [comment]
It's impossible to change artifacts released to maven central. You could backport the fix and try asking @timmolter to release a 2.1.1 . You'd need to make branch rooted in xchange-2.1.0 tag for that.

**Pull request merged**
