### PR TITLE
Test with java 9

### LINKED ISSUE #2337: Port to java9
1. [x] make RestProxyFactory mockable
2. [ ] change tests so they don't require PowerMockito
    - [ ] acx
    - [x] anx
    - [x] bitmarket
    - [ ] bleutrade
    - [ ] btcmarkets
3. [ ] upgrade maven in travis
4. [ ] add java9 in travis

@timmolter please assign to me

### PR DESCRIPTION
**Pull request by rafalkrupinski**
Add jdk9 run to travis.

Fixes #2337

### CODE REVIEW

**Comment by rafalkrupinski** [comment]
@timmolter can you re-run travis build for this PR? There was some problem with travis :)

**Comment by timmolter** [comment]
did it.

**Comment by rafalkrupinski** [comment]
Looks like Java9 will require maven 3.5 and PowerMockicto is unsupported.
@timmolter WDYT?

**Comment by timmolter** [comment]
We had similar issues to this when upgrading to Java 8.

Here's a related thread: https://github.com/grpc/grpc-java/issues/3633

I'm not really sure what to do at this point. Any help is appreciated.

**Comment by rafalkrupinski** [comment]
The @generated isn't a big issue.

 the problem is some tests using powermockito. The ones I've checked were
using it to go around (perceived?) limitations of rescu.
I'll have a another look at them and if they don't test to much, and
mocking up rescu is really necessary, I'll go ahead and make a PR to make
it possible with standard mockito.

**Comment by rafalkrupinski** [comment]
@timmolter right now it's failing on missing classes that I've just added to Rescu. Might be the cache on Travis or the new Rescu build is not yet in snapshot repo.
Anyway, even if it had compiled, it would still fail on Bleutrade tests as I've only refactored Bitmarket tests for now. I'll continue with the rest of failing exchanges in the coming days unless you want to do a code review and have any remarks.

**Comment by timmolter** [comment]
Take your time. :) There is a new PR in the queue relying on Powermockito. Should I merge it and then you remove it or ask them to remove it before I merge the PR?

**Comment by brilliantnut** [comment]
@timmolter, If you're talking about https://github.com/timmolter/XChange/pull/2356, I'm happy to remove the test altogether, however, writing the test without PowerMockito is probably too hard right now.

**Comment by rafalkrupinski** [comment]
@brilliantnut I'd rather you keep the test and have it merged, it's easy enough for me to refactor it later on. I'll be merging from master every now and then anyway.

**Comment by rafalkrupinski** [comment]
@brilliantnut Actually, you could change to standard Mockito once my the latest Rescu snapshot lands in public repo.
@mmazi, can you offer some help on this? I thought develop builds would deploy to snapshot repo. Did I miss something?

**Comment by brilliantnut** [comment]
@rafalkrupinski merging my PR would also require merging your dependency changes in the parent pom.xml _or_ me duplicating those changes in my PR. As my PR is already ready to merge, and this one is some way out, I feel that we should merge mine now, and then you include that in your refactoring later.

@timmolter your thoughts?

**Comment by mmazi** [comment]
> @mmazi, can you offer some help on this? I thought develop builds would deploy to snapshot repo. Did I miss something?

I've re-run the Travis build and [the new snapshots are now available](https://oss.sonatype.org/content/repositories/snapshots/com/github/mmazi/rescu/).

(There's [a test](https://github.com/mmazi/rescu/blob/develop/src/test/java/si/mazi/rescu/RestInvocationHandlerTest.java#L445) in rescu that occasionally fails that has prevented push to snapshot repo.)

You should make sure, however, that you're using the 2.0.2-SNAPSHOT version of rescu. (I think the develop branch of XChange now uses 2.0.1.)

**Comment by rafalkrupinski** [comment]
Splitting to smaller PRs to avoid long-running branch and conflicts

**Pull request closed without merging**
