### PR TITLE
krakenticker open

### PR DESCRIPTION
**Pull request by jcuypers**

### CODE REVIEW

**Comment by timmolter** [comment]
can you also fix the broken unit test?

**Comment by jcuypers** [comment]
Is there a way to combine these commits into one?  the test fails because of this.  I validated it locally. anyway if not I will figure out in the coming days.

**Comment by timmolter** [comment]
I merged it. Hopefully it will pass now.

**Comment by jcuypers** [comment]
thanks. looks ok

2017-12-05 13:05 GMT+02:00 Tim Molter <notifications@github.com>:

**Pull request merged**
