### PR TITLE
[kraken] Various bug fixes

### PR DESCRIPTION
**Pull request by henryxwong**

### CODE REVIEW

**Comment by andre77** [comment]
after this changes, i get NPE:

`
at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenOrder(KrakenTradeServiceRaw.java:157)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenLimitOrder(KrakenTradeServiceRaw.java:146)
	at org.knowm.xchange.kraken.service.KrakenTradeService.placeLimitOrder(KrakenTradeService.java:58)
	at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
`

@henryxwong 
you create in the class org.knowm.xchange.kraken.dto.trade.KrakenStandardOrder such a field 
  private final Map<String, String> closeOrder;
to access it like this

` closeOrder = new HashMap<>();
      closeOrder.put("ordertype", orderType.toString());
      closeOrder.put("price", price);
      closeOrder.put("price2", secondaryPrice);`

`
 krakenStandardOrder.getCloseOrder().get("ordertype"), krakenStandardOrder.getCloseOrder().get("price"),
          krakenStandardOrder.getCloseOrder().get("price2")`

you must be kidding me...

@timmolter 
can we revert it?

**Comment by timmolter** [comment]
OK, I reverted it.

**Comment by henryxwong** [comment]
alright, my fault, haven't test the flow without close order after making this change, will fix it.

**Comment by henryxwong** [comment]
@andre77 
There are complications that the simple NPE fix cannot be done on top of this PR (code reformatted, I squashed my commits)
I already make a new PR #2380 but Tim also rejected it. Would you please advise how to proceed?

**Comment by timmolter** [comment]
I rejected it because the PR contain more than just the NPE fix. I'm not against the NPE fix by itself.

**Comment by henryxwong** [comment]
I understand your good intentions. Just too much complications make it hard to proceed with simple changes. Any I make another NPE fix on top of this PR #2420, please see if it is ok for you to reapply this change and NPE.

**Pull request merged**
