### PR TITLE
Fixed HTTP 404 error for BTCChina

### PR DESCRIPTION
**Pull request by ezhik97**
BTCChina fail with 404 error while try to get balance.

### CODE REVIEW

**Comment by jheusser** [comment]
@ezhik97 The docs don't mention `api.btcchina.com` but `data.btcchina.com`:
https://www.btcchina.com/apidocs/spot-exchange-market-data-rest-api-zh.html

Maybe `api.btcchina.com` is only for authenticated calls?

**Comment by ezhik97** [comment]
May be I commit too early.
I have updated from 4.0 to the current 4.2 snapshot.
And one of my test is broken. What happened?
The test calls BTCChinaAccountService.getAccountInfo()
It is authenticated call.
And I get:

```
17:53:46.375 [main] DEBUG si.mazi.rescu.HttpTemplate - Executing POST request at https://data.btcchina.com/api_trade_v1.php
17:53:51.043 [main] DEBUG si.mazi.rescu.HttpTemplate - Request http status = 404

si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 404
```

**Comment by jheusser** [comment]
Can you enable TRACE logging for si.mazi.rescu? Be careful not to paste password/api keys here 😄

**Comment by timmolter** [comment]
Any status updates on this PR?

**Comment by ezhik97** [comment]
```
DEBUG [2017-04-15 11:09:12,340] si.mazi.rescu.HttpTemplate: Executing POST request at https://data.btcchina.com/api_trade_v1.php
TRACE [2017-04-15 11:09:12,340] si.mazi.rescu.HttpTemplate: Request body = {"id":1,"method":"getAccountInfo","params":[]}
TRACE [2017-04-15 11:09:12,341] si.mazi.rescu.HttpTemplate: Request headers = {Authorization=Basic *, Json-Rpc-Tonce=1492254552123000, Accept=application/json, Content-Type=application/json}
TRACE [2017-04-15 11:09:12,352] si.mazi.rescu.HttpTemplate: Header request property: key='Accept-Charset', value='UTF-8'
TRACE [2017-04-15 11:09:12,353] si.mazi.rescu.HttpTemplate: Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7'
TRACE [2017-04-15 11:09:12,353] si.mazi.rescu.HttpTemplate: Header request property: key='Authorization', value='Basic *'
TRACE [2017-04-15 11:09:12,353] si.mazi.rescu.HttpTemplate: Header request property: key='Json-Rpc-Tonce', value='1492254552123000'
TRACE [2017-04-15 11:09:12,354] si.mazi.rescu.HttpTemplate: Header request property: key='Accept', value='application/json'
TRACE [2017-04-15 11:09:12,354] si.mazi.rescu.HttpTemplate: Header request property: key='Content-Type', value='application/json'
=============ERROR========
si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 404
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy54.getAccountInfo(Unknown Source)
	at org.knowm.xchange.btcchina.service.rest.BTCChinaAccountServiceRaw.getBTCChinaAccountInfo(BTCChinaAccountServiceRaw.java:38)
	at org.knowm.xchange.btcchina.service.rest.BTCChinaAccountService.getAccountInfo(BTCChinaAccountService.java:48)
	at com.pozheg.cloudbot.market.BtccConnector.getBalance(BtccConnector.java:47)
	at com.pozheg.App.run(App.java:159)
	at com.pozheg.App.run(App.java:35)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at com.pozheg.App.main(App.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
TRACE [2017-04-15 11:09:22,991] si.mazi.rescu.HttpTemplate: Http call returned 404; response body:
<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>404 Not Found</h1></center><hr><center>nginx</center></body></html><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Pull request closed without merging**
