### PR TITLE
I have update the bitbay.json file

### PR DESCRIPTION
**Pull request by makarid**
Hello, i have update the bitbay.json file in order to include the new currency pairs that this exchange supports.Because this is the first time that i am doing a pull request,please check it if i have write something wrong.Thanks a lot

### CODE REVIEW

**Comment by timmolter** [comment]
There seems to be an issue. make sure to sync up your fork with the main fork (upstream) and fix any conflicts.

**Comment by makarid** [comment]
Hello, do you mean the develop branch or the master branch? Thanks

**Comment by timmolter** [comment]
develop

**Comment by makarid** [comment]
i have clone the project again to a new folder.I am trying to push the modified project using "git push" command but i get a message that i haven't permission to push the project

**Comment by timmolter** [comment]
you have to clone **YOUR** fork

**Comment by makarid** [comment]
Thanks a lot for your help.I am sorry about all that it was my first time.Now i know that every change i want to make i upload it to my fork and then i create a push request in order to update your fork.Thanks.

**Pull request closed without merging**
