### PR TITLE
[xchange-core] make xchange-core less prone to accidental refactors p…

### PR DESCRIPTION
**Pull request by jnorthrup**
…er  #2431

when any module has /x/y.json file and it is of a value to refactor or clone the package and specialize the package names, intellij will cause great havoc refactoring without tedious measures taken

### CODE REVIEW

**Comment by jnorthrup** [comment]
there appears to be some event where intellij opened many files and saved different line-endings with this.  i went back with dos2unix and minimized the noise but there may have already been some mixed line endings in the source tree.

viewing as https://github.com/timmolter/XChange/pull/2432/files?w=1 will ignore ws changes

**Comment by jnorthrup** [comment]
@timmolter please review -- this doesn't change anything about the project .... but, with an alternate layout via shell scripts and 90% of the pom I get some impressive build and test thruputs for an uberjar

```
[WARNING] Tests run: 683, Failures: 0, Errors: 0, Skipped: 2
[...]
[INFO] Building jar: I:\Xpolyglot\xchange-all\target\xchange-all-4.3.5-SNAPSHOT.jar
[...]
[INFO] xchange-parent ..................................... SUCCESS [  0.643 s]
[INFO] XChange Speedball .................................. SUCCESS [ 38.055 s]
[...]
[INFO] BUILD SUCCESS
[...]
[INFO] Total time: 01:15 min
```

**Comment by timmolter** [comment]
Does anyone have arguments for or against fully-qualified package names in the `test/resources` folder? I never ran into issues with things how they are.
@jnorthrup It's tough to work with this giant monolithic PR. Can you split this into small atomic PRs? 
Also, what script did you use to convert dos 2 unix?

**Comment by jnorthrup** [comment]
i did dos2unix `find -name *java -name *json` on ubuntu windows -- there are apparently mixed commits of both

**Comment by jnorthrup** [comment]
im just afraid the line-endings events (likely due to intellij AST traversal) will cause conflicts if other mods go in ahead of these. 

the net result is that maven-assembly and shade plugins are this much closer to succeeding with this many jarfiles being merged and potential string collisions that leak into non-test code.  coverage tools should show a different picture than before, but i didn't capture those before and after.

**Comment by jnorthrup** [comment]
i also wanted to bring this to your attention --  https://stackoverflow.com/a/25908693/1577005 this can be sorted out with one commit also to move integration tests into src/test-integration/java so that continuous testing is uncomplicated in eclipse/intellij

**Comment by jnorthrup** [comment]
alright so i have hatched a plan, since line endings and formatting go hand in hand they can be mavenized.  integration tests can be teased out into a seperate package, and i can build up a seperate branch from the before and after.  the differences can be staged per module.

**Comment by jnorthrup** [comment]
i can add formatter, and keep this hashref in case the formatter goes horribly wrong.  can also massage the integration tests out of the way for dailly dev. per gentler failsafe plugin

**Comment by jnorthrup** [comment]
resuming this in #2443 , basically more cosmetic commits broken out per module towards better automation results and smaller deltas moving forward.  autoformatters make golang developers pretty happy, i just say "so does maven" when they call it a unique benefit

**Pull request closed without merging**
