### PR TITLE
Bitstamp added euro support

### PR DESCRIPTION
**Pull request by Achterhoeker**
Added euro support on bitstamp.
Implemented:
 * Balance
 * Order books
 * placing limit order
 * query open orders

### CODE REVIEW

**Comment by timmolter** [comment]
can you check on the failed build?

**Comment by Achterhoeker** [comment]
@timmolter  Done, tests are passing now.
I saw that you also closed the corresponding ticket. But i didn't implement all api calls. (only the one my bot needs and i can test)

**Comment by mmazi** [comment]
Thanks, @Achterhoeker . I'll merge this after I refactor it a bit.

**Comment by mmazi** [comment]
Replaced by #1247.

**Pull request closed without merging**
