### PR TITLE
[Binance] Currency returned in balance cannot use ==

### LINKED ISSUE #2137: [Binance] Currency returned in balance cannot use ==
It seems that balance contains new currency instances instead of using the available constants. Also, the AccountService does not use the Exchange's time stamp

### PR DESCRIPTION
**Pull request by tdiesler**
resolves #2137

### CODE REVIEW

**Comment by uwemaurer** [comment]
I think it would be better to avoid this extra request to get the time before doing the actual request.
Is it really needed?

**Comment by tdiesler** [comment]
I believe so. If the client's system clock is slightly out of sync with that of the binance system, these requests will fail. Hence relying on these clocks to be in sync introduces another factor of uncertainty.

**Comment by uwemaurer** [comment]
yes true. A disadvantage is the extra roundtrip and that the rate limit is reached faster then. Maybe the time request could be done once during initialization to calculate the delta between client and server time. And for a new request it could add the delta then to the clients time to adjust it to the server time.

**Comment by tdiesler** [comment]
Yes, that is good idea - let me see to it

**Pull request merged**
