### PR TITLE
Use the base64 dependency via Maven instead of bundling it.

### PR DESCRIPTION
**Pull request by hegjon**
Makes it easier to include into Linux distros. See https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries#Why_no_Bundled_Libraries

### CODE REVIEW

**Comment by timmolter** [comment]
Any idea where the source code is for version 2.3.8?

**Comment by hegjon** [comment]
Fedora uses this tarball https://github.com/omalley/base64/archive/release-2.3.8.tar.gz

**Comment by timmolter** [comment]
Strange. The version inside the source file says:

     * @author Robert Harder
     * @author rob@iharder.net
     * @version 2.3.7
 
Maybe just sloppy bookkeeping.

**Comment by hegjon** [comment]
Thanks for merging, I plan to make a Fedora package for XChange when the dependencies have been approved.

https://bugzilla.redhat.com/show_bug.cgi?id=1231570
https://bugzilla.redhat.com/show_bug.cgi?id=1231457

**Comment by timmolter** [comment]
Cool. I'm happy to help. What's XChange going to be used for specifically?

**Comment by hegjon** [comment]
Glad to hear. The main use case is as a dependency for MultiBit HD.

**Comment by hegjon** [comment]
XChange package have been added for review in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1303764

**Pull request merged**
