### PR TITLE
Cryptsy public API bug fix for v3.0.0-SNAPSHOT, Kraken general enhancements, Trade Builder additions

### PR DESCRIPTION
**Pull request by ww3456**
re: CryptsyBasePollingService now that it contains both the public and private API does it really make sense for it to stay templated in its current form? 

The Cryptsy fix was to stop the URL being generated as http://pubapi.cryptsy.com/api/api.php?method=orderdatav2
but instead http://pubapi.cryptsy.com/api.php?method=orderdatav2

### CODE REVIEW

**Comment by timmolter** [comment]
Thank you.

**Comment by timmolter** [comment]
FYI, I just pushed a commit that removed all the generics from Cyptsy to be consistent with the rest of XChange.

**Comment by ww3456** [comment]
That Cryptsy class is looking cleaner. However, when you subsequently removed generics from PoloniexBasePollingService the public API broke. e.g. it should have been sending 
https://poloniex.com/public?command=returnTicker but was sending 
https://poloniex.com/tradingApi?command=returnTicker
I've reverted to the previous version of this Poloniex class and it works fine. I'm not sure of the exact intent behind these recent BasePollingService changes so will leave it to others to decide how best to fix this. Thanks!

**Comment by timmolter** [comment]
@ww3456 Good catch. Thanks. I see what the problem is now. I will check all exchange modules and fix appropriately.

**Comment by timmolter** [comment]
@ww3456 I pushed a fix.

**Comment by ww3456** [comment]
@timmolter great, this is working now. For the record I now have the latest develop 3.0.0-SNAPSHOT running OK on BTC-E, Bitfinex, Cryptsy, Kraken and Poloniex for both market data and trading.

**Comment by timmolter** [comment]
Excellent. Thanks for telling me which exchanges are working for you too!

**Pull request merged**
