### PR TITLE
Bitfinex errors solved and added new coins

### PR DESCRIPTION
**Pull request by Achterhoeker**
Bitfinex order numbers are now to high to fit in a signed int. (resulting in errors at placing orders and retrieving open orders. Error at place order is a real problem, the order is executed, but result results in an error)
Increased order number to long type.
Added new coins, also conversion of dsh to dash

### CODE REVIEW

**Comment by ezhik97** [comment]
Why you use double for order num instead long?

**Comment by Achterhoeker** [comment]
it was a mistake from me. Latest is already based on a long. Op 24 mrt. 2017 8:10 a.m. schreef ezhik97 <notifications@github.com>:Why you use double for order num instead long?

**Comment by ezhik97** [comment]
Also it is needed to fix BitfinexTradeServiceRaw:
new BitfinexCancelOrderRequest(String.valueOf(exchange.getNonceFactory().createValue()), Integer.valueOf(orderId)));

orderId is not parse into Integer.

**Comment by Achterhoeker** [comment]
@ezhik97 thanks, that was indeed also needed.

**Comment by andre77** [comment]
in the class BitfinexTradeServiceRaw.java, there are still expressions like 
Integer.valueOf(offerId)

please replace the Integer with Long

**Comment by Achterhoeker** [comment]
@andre77 you are right. I had now some more time to clean up the mess i made. Are you ok now with the latest state ? I think i've now transformed all id's into longs.

**Pull request merged**
