### PR TITLE
[Kucoin] add Kucoin exchange

### PR DESCRIPTION
**Pull request by odrotleff**
Needs (a lot) more tests and exception handling, but should integrate Kucoin as best as their API allows (hopefully).

### CODE REVIEW

**Comment by timmolter** [comment]
Looks like something isn't compiling. Can you look into it?

**Comment by odrotleff** [comment]
Yeah I think I will finish with the basics this weekend. Still had some stuff on my todo but noticed that someone else started on the Kucoin implementation. So I wanted to get it out there that I work on it so no work is duplicated.

**Comment by odrotleff** [comment]
#2074

Still have to write some tests and there are probably a few bugs here or there (cant really test extensively if I lose money doing it). Is the code format checked during CI? Because I noticed just now that there is also an eclipse configuration in the parent project and used google style for all of this.

**Comment by timmolter** [comment]
Formatting isn't checked, but we ask that you do use the supplied formatters.

**Pull request merged**
