### PR TITLE
Added bitcoin.de implementation for market data 

### PR DESCRIPTION
**Pull request by bryan4887**

### CODE REVIEW

**Comment by timmolter** [comment]
excellent addition! 

Does the ticker and orderbook require an API key or is it completely public?

**Comment by bryan4887** [comment]
It requires an API key unfortunately, and they're not exactly quick about issuing them either.

**Comment by timmolter** [comment]
@bryan4887 do you also have to have an account there or can anyone request an API key?

**Comment by bryan4887** [comment]
@timmolter good question.  I registered with a login and everything, but I didn't input any financial info.

**Comment by timmolter** [comment]
@bryan4887 Cool, thanks.

**Pull request merged**
