### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by timmolter** [comment]
@npomfret What's the current situation with BTC-E? I thought they shut down. Is it run somewhere else under a different name now?

**Comment by cymp** [comment]
@timmolter  They are now https://wex.nz/

**Comment by timmolter** [comment]
Just curious - were all user accounts upheld? How was the transition?

**Comment by cymp** [comment]
I'm not sure everyone got their money back : https://www.coindesk.com/btc-e-back-online-refund-efforts-anything-smooth/

**Comment by cymp** [comment]
There is a bitcointalk topic somewhere as well.

**Comment by Achterhoeker** [comment]
@timmolter  Some of the assets are converted in debt-tokens. (like bitfinex did in the past)
So there is a possibility everything will be returned. (The assets confiscated by the fbi are converted in debt tokens) My trading bot is running good on the new exchange. (like it always did on btc-e)

**Comment by timmolter** [comment]
Thanks, everyone.

**Comment by timmolter** [comment]
Should we change the module name, namespace and class names etc. to WEX? I can do it...

**Comment by npomfret** [comment]
I guess we should.

**Pull request merged**
