### PR TITLE
Fundinginfo improvements

### PR DESCRIPTION
**Pull request by mmazi**
Opening a PR so we can continue the conversation here. @timmolter You can leave this for me to merge when it's ready (it's not ready yet).

### CODE REVIEW

**Comment by mmazi** [comment]
Tested: https://github.com/timmolter/XChange/pull/1406#issuecomment-292894580

**Comment by timmolter** [comment]
@mmazi Ready to merge this? I can do a release today or perhaps this weekend. Any important rescu updates?

**Comment by mmazi** [comment]
Not yet ready. I think it's still necessary to change `FundingRecord.status` to an enum to make the API is not sufficiently generic.

I can do the coding, but I'd need help with testing. I can test Kraken and Poloniex, but not easily Bitfinex, BTCChina, and OkCoin. @kisapmata , can you help here? I'd also like some input about what status enum values are appropriate for these three exchanges.

@timmolter I don't think there is anything important in rescu beyond 1.9.0.

**Comment by mmazi** [comment]
I've pushed the code with `enum Status`, and also contacted some exchanges about the possible values of what they return as as deposit/withdrawal status.

@kisapmata The code for Bitfinex, BTCChina, and OkCoin needs to be updated (and tested): map the values returned from the exchanges to appropriate enum values. Do you think you can find the time? (Replace all usages of the deprecated FundingRecord constructor with the new constructor.)

Also, if there are other values of the Status enum you'd like included, please let me know. I'd like to keep these at a minimum though, but I might have missed some.

**Comment by mmazi** [comment]
@kisapmata Here's the OkCoin status mapping from their docs:

status: recharge status (-1:Failure;0:Wait Confirmation;1:Complete), withdrawal status (-3:Revoked;-2:Cancelled;-1:Failure;0:Pending;1:Pending;2:Complete;3:Email Confirmation;4:Verifying5:Wait Confirmation)

**Comment by mmazi** [comment]
Here's the response from BitFinex support regarding the statuses they return:

> The possible return values of the status field are:
> 
>  - PENDING
>  - PROCESSING
>  - PENDING APPROVAL
>  - PROCESSING
>  - COMPLETED

**Comment by kisapmata** [comment]
Hi All, sorry its been super busy at work. Can you let me know what and how
exactly you want me to do. What has been done and whats pending and which
branch to checkout etc.? I understand you want to convert the status to
enum. Just want to be clear before I start on anything.

Regards,

**Comment by mmazi** [comment]
Hi @kisapmata , great to have you here :)

Check out this branch (`fundinginfo-improvements`). It already contains enum Status. Then what needs to be done is this:

The code for Bitfinex, BTCChina, and OkCoin needs to be updated (and tested): the values returned from the exchanges need to be mapped to appropriate enum Status values. (Replace all usages of the deprecated FundingRecord constructor with the new constructor.)

**Comment by kisapmata** [comment]
Hi, I noticed that in Poloniex below we are equating the PENDING with
PROCESSING? I need help to finalized the list of status.

if ("PENDING".equals(statusStr) && status == null) {
  status = FundingRecord.Status.PROCESSING;
}


I was initially thinking of adding below statuses for OKCOIN and BITFINEX.
But looking at poloniex, seems I can map all below (except for REVOKED) to
PROCESSING.? I assume revoke can be added as new status?

  WAIT_CONFIFMATION
  REVOKED,
  EMAIL_CONFIRMATION,
  VERIFYING,
  PENDING_APPROVAL,
  PENDING

**Comment by mmazi** [comment]
> seems I can map all below (except for REVOKED) to
PROCESSING.?

I agree.

> I assume revoke can be added as new status?

Shouldn't REVOKED be mapped to CANCELLED?

**Comment by kisapmata** [comment]
the java comment in FundingRecord on CANCELLED is that it is
user-cancelled. i think revoked is cancelled by the exchange?  or shall we
change the java comment?

**Comment by mmazi** [comment]
Ah, I see they have both Cancelled and Revoked. I've asked the OkCoin support.

It seems probable to me that all negative statuses mean that the transaction didn't go through, and never will, so they are final statuses. So I suggest REVOKED is mapped either to CANCELLED or FAILED -- your choice. We may fix it later if necessary. I would not add a new status.

**Comment by kisapmata** [comment]
Hi all, i have created the pull request for my commits.

https://github.com/timmolter/XChange/pull/1446

**Comment by dave0688** [comment]
Hi guys, 
thanks all for your awesome work here. 
Short question: When will these changes (I'm mainly interested in funding info for bitfinex) be available over maven central? The most recent version (4.2.1) does not seem to have those changes.

**Comment by timmolter** [comment]
@dave0688 https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions

**Comment by timmolter** [comment]
No release notes, sorry. I'm not sure about the Bitfinex funding. Unfortunately you'll just have to watch the code, or code it yourself and submit a PR for it.

**Comment by kisapmata** [comment]
i thought we included bitfinex for funding history, and also, you can check
the demo classes for usage.

On 22 Aug 2017 02:33, "Tim Molter" <notifications@github.com> wrote:

No release notes, sorry. I'm not sure about the Bitfinex funding.
Unfortunately you'll just have to watch the code, or code it yourself and
submit a PR for it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/timmolter/XChange/pull/1432#issuecomment-323818748>,
or mute
the thread

**Pull request merged**
