### PR TITLE
ripple withdrawls - introduced concept of WithdrawFundsParams to support more complex addresses

### PR DESCRIPTION
**Pull request by npomfret**
I've not yet implemented an XRP withdrawal, but the API at least supports it now.

[GDAX] previous 'moveFunds' functionality now in its own method
[GDAX] fixed withdraw funds

### CODE REVIEW

**Comment by npomfret** [comment]
@timmolter this fixes https://github.com/timmolter/XChange/issues/1636

**Comment by npomfret** [comment]
Have moved the 'moveFunds' functionality out of the withDraw method.  It's still there in case people need to use it (I assume it was written for a reason)

**Comment by npomfret** [comment]
@timmolter thanks for merging.  it seems to have broken the build though.  i can't tell from the build output whats wrong

**Comment by timmolter** [comment]
@npomfret Hey, thank you! It looks like a failure to deploy the snapshots, no fault of yours. I've restarted it.

**Pull request merged**
