### PR TITLE
Coinbase Exchange: retrieve full orderbook, start of account service

### PR DESCRIPTION
**Pull request by jheusser**
_Don't merge yet, see comments below_

- retrieve full orderbook from MarketDataService
- start of AccountService. I am really having issues getting the authentication (in `CoinbaseExDigest`) to work. Not sure what I'm doing wrong. You are supposed to decode the base64 secret key before instantiating a `SecretKeySpec`. Then just base64 encode the digest result. I'm putting this here in case someone else could have a look -- otherwise I'll get back to it later.

### CODE REVIEW

**Comment by jheusser** [comment]
Ok got this to work. Will push more tomorrow.

**Comment by jheusser** [comment]
This is finished for now, ability to place/cancel/get account info/list open orders via REST.

**Comment by bryan4887** [comment]
It appears as though I am doing something dumb, or this isn't resolved...:
```
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(CoinbaseExExchange.class.getName());
PollingMarketDataService service = exchange.getPollingMarketDataService();
System.out.println(service.getOrderBook(CurrencyPair.BTC_USD));
```

yields:

```
Exception in thread "main" java.lang.NullPointerException: Input string was null.
	at si.mazi.rescu.utils.Base64.decode(Base64.java:1074)
	at si.mazi.rescu.utils.Base64.decode(Base64.java:1058)
	at com.xeiam.xchange.coinbaseex.service.CoinbaseExDigest.createInstance(CoinbaseExDigest.java:26)
	at com.xeiam.xchange.coinbaseex.service.polling.CoinbaseExBasePollingService.<init>(CoinbaseExBasePollingService.java:31)
	at com.xeiam.xchange.coinbaseex.service.polling.CoinbaseExMarketDataServiceRaw.<init>(CoinbaseExMarketDataServiceRaw.java:20)
	at com.xeiam.xchange.coinbaseex.service.polling.CoinbaseExMarketDataService.<init>(CoinbaseExMarketDataService.java:26)
	at com.xeiam.xchange.coinbaseex.CoinbaseExExchange.applySpecification(CoinbaseExExchange.java:25)
	at com.xeiam.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:56)
	at net.bh.archive.archiver.CoinbaseExchange.main(CoinbaseExchange.java:24)
```


Thoughts?

**Comment by jheusser** [comment]
#969 might have solved this. Try with latest develop.

**Comment by bryan4887** [comment]
Fantastic.  Thanks for the tip, @jheusser

**Pull request merged**
