### PR TITLE
Implementing equals() and hashCode() for UserTrade.

### PR DESCRIPTION
**Pull request by stevenuray**
I'm a user of XChange but this is my first contribution. 

I would benefit from these modifications, and I thought others would too. 

If I am not following accepted conventions, proper PR protocol, etc please let me know and I'll try to make necessary changes.

### CODE REVIEW

**Comment by andre77** [comment]
just out of curiosity, why do you need those methods?

**Comment by stevenuray** [comment]
@andre77

I have an object in my application that has a UserTrade as a property and has other properties that add data about the UserTrade that is specific to my application.  

I want to implement equals() and hashCode() on my custom object so that two objects with the same values are considered equal, and this would be made easier/cleaner for me if UserTrade implemented equals() and hashCode() so that two UserTrades with equal values are considered equal. 

I assumed other users would desire the same behavior from UserTrades. 

Perhaps this was an incorrect assumption.

If this isn't going to be a net positive for the community, I'll close the PR.

**Comment by andre77** [comment]
@stevenuray 
i do not mind to add those methods, totally fine to me
in your case, you probably just could extend the existing UserTrade and create a new class containing all the properties required by your application. In that new class you can than add what ever you like, the hash and equals method, which would use the properties from the super classes etc.

just my 2c

Marry Christmas! :-)

**Comment by timmolter** [comment]
I'm not yet against it, but haven't had time yet to take a close look. Please don't close this PR yet. Thanks!

**Comment by stevenuray** [comment]
@andre77 

I agree extending the class would work too, in this case.

Thanks for the reviews/merge, and also all the work on the XChange project!

Happy Holidays!

**Pull request merged**
