### PR TITLE
fix https://github.com/timmolter/XChange/issues/1499

### PR DESCRIPTION
**Pull request by npomfret**
removed the static state from the YoBitOrderBookDeserializer which was causing orders from different markets to appear in the same order book

### CODE REVIEW

**Comment by npomfret** [comment]
Hmm, my pr seems to have @timmolter's commits in it?  Not sure what I've done there.

**Comment by timmolter** [comment]
@npomfret Could you close this and submit a new PR. You probable just need to get all synced up first.

**Comment by npomfret** [comment]
Sure, have something else to add anyway

**Comment by npomfret** [comment]
Hmm, I'm a bit stuck.  No matter what I do git wants to include those commits...

**Comment by timmolter** [comment]
I'm not sure how to fix it. Maybe google has an answer?

**Pull request closed without merging**
