### PR TITLE
Changing / removing deprecated methods

### PR DESCRIPTION
**Pull request by Muffon**
- changing deprecated methods

### CODE REVIEW

**Comment by timmolter** [comment]
@Muffon Can you take a look into what the conflicts are?

**Comment by Muffon** [comment]
How/Where?

**Comment by timmolter** [comment]
You'll need to update your branch with new commits from `develop`, resolve those conflicts and push the updated/resolved branch to GitHub.

**Comment by Muffon** [comment]
ok

**Comment by timmolter** [comment]
Any progress on this? I'd love to merge this!

**Comment by Muffon** [comment]
Hi, I am sorry, no time to do this yet.

**Comment by timmolter** [comment]
closing due to no activity

**Pull request closed without merging**
