### PR TITLE
api v2 on authenticated api calls

### PR DESCRIPTION
**Pull request by cymp**

### CODE REVIEW

**Comment by cymp** [comment]
I have no clue how to resolve those conflicts, the git bash client is not telling me there are any conflicts, and the web client has its "resolve conflicts" button greyed out. I am not a big git expert, any suggestions?

**Comment by timmolter** [comment]
Did you first sync up with my upstream repo?

**Comment by cymp** [comment]
I forked about 15 hours ago and then worked on it.

**Comment by timmolter** [comment]
then you'll have to sync up, resolve the issues and create a new PR. I also did a new release, and there is a new version within the last 15 hours.

**Pull request closed without merging**
