### PR TITLE
Ticker bidSize askSize

### PR DESCRIPTION
**Pull request by devinrsmith**
Some exchanges provide the size in addition to the price for ticker calls. The size information should be passed along when available. Implemented the additional fields for itBit.

### CODE REVIEW

**Comment by timmolter** [comment]
what exactly do those fields represent?

**Comment by aleks-azen** [comment]
@timmolter on the exchanges that send this data, the represent the lot size of the best bid and best ask

**Comment by devinrsmith** [comment]
`bidSize` represents the instantaneous size at price `bid`
`askSize` represents the instantaneous size at price `ask`

**Comment by timmolter** [comment]
it'd be nice if the description of the fields were added as Javadoc comments.

**Comment by devinrsmith** [comment]
I've updated the constructor javadoc to be more explicit. If there is a more appropriate place for the javadoc, let me know!

**Pull request merged**
