### PR TITLE
Kraken: Retrieve symbols and pairs from Kraken exchange. 

### PR DESCRIPTION
**Pull request by Achterhoeker**
Retrieve symbols and pairs from Kraken exchange. (no more hardcode translations needed)
Updated with new pairs and symbols from kraken exchange for tests.
Updated according new api format with market fees and leverage buy and sell information

### CODE REVIEW

**Comment by Achterhoeker** [comment]
@timmolter This is the new pull request with all my changes. All test are running now.

**Comment by npomfret** [comment]
@Achterhoeker 

My app is failing to get the currency scale for EUR now.  Is this due to these recent changes?

**Comment by npomfret** [comment]
... i thin k is it.  Looks like maybe the `krakenAssets` are no longer being added to the currency metadata in `adaptToExchangeMetaData`.

@timmolter could we revert until it's fixed?

**Comment by Achterhoeker** [comment]
@npomfret Ai, it seems you are right: 
Kraken: raw metaData: ExchangeMetaData [currencyPairs={USDT/USD=CurrencyPairMetaData [tradingFee=0.002, minimumAmount=5.0, maximumAmount=null, priceScale=4], XRP/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=6], XRP/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=6], ETC/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=8], XRP/CAD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], ETH/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=6], DASH/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], XRP/JPY=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=4], DASH/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], ETH/GBP=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=5], LTC/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.10000000, maximumAmount=null, priceScale=5], XMR/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.100000000, maximumAmount=null, priceScale=6], ETH/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=5], ETH/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=5], BCH/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=6], REP/CAD=CurrencyPairMetaData [tradingFee=null, minimumAmount=0.300000000, maximumAmount=null, priceScale=6], MLN/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.100000000, maximumAmount=null, priceScale=6], ZEC/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], ETH/JPY=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=3], XRP/GBP=CurrencyPairMetaData [tradingFee=null, minimumAmount=30.00000000, maximumAmount=null, priceScale=5], ZEC/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], ETC/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=8], EOS/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=5], EOS/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=5], ZEC/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=6], ETC/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=5], EOS/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], ETC/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=5], REP/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=6], BTC/CAD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.002000000, maximumAmount=null, priceScale=3], GNO/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], GNO/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=5], DOGE/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=3000.00000, maximumAmount=null, priceScale=8], BCH/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=4], BCH/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=4], BTC/JPY=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.002000000, maximumAmount=null, priceScale=1], XMR/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.100000000, maximumAmount=null, priceScale=5], REP/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=5], BTC/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.002000000, maximumAmount=null, priceScale=3], DASH/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=6], BTC/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.002000000, maximumAmount=null, priceScale=3], ICN/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=5], GNO/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=6], XMR/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.100000000, maximumAmount=null, priceScale=5], BTC/GBP=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.002000000, maximumAmount=null, priceScale=3], MLN/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.100000000, maximumAmount=null, priceScale=5], XLM/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], XRP/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=8], GNO/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, maximumAmount=null, priceScale=6], XLM/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], ICN/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], LTC/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.10000000, maximumAmount=null, priceScale=5], LTC/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.10000000, maximumAmount=null, priceScale=6], EOS/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], ETH/CAD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=5], REP/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=5], REP/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=5], XLM/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=300.000000, maximumAmount=null, priceScale=8]}, currencies={}, publicRateLimits=[RateLimit [calls=1, timeSpan=6, timeUnit=SECONDS]], privateRateLimits=null, shareRateLimits=false]

All pairs are present. Currency metadata seems missing.
My bot is running this code for several days without problems, but it isn't using this currency meta data. It also seems that this feature isn't test by any unit test.

Sorry for missing it. 
@npomfret Are you able to add it and test it ? I'm currently limited in my time. First possibility i could change it is on Friday.

**Comment by Achterhoeker** [comment]
@npomfret New pull request added with suggested change

**Pull request merged**
