### PR TITLE
lots of fundingHistroy stuff 

### PR DESCRIPTION
**Pull request by npomfret**

### CODE REVIEW

**Comment by npomfret** [comment]
Thanks.  Will there be a new snapshot soon? https://oss.sonatype.org/content/repositories/snapshots/org/knowm/xchange/xchange-bitfinex/

**Comment by timmolter** [comment]
https://travis-ci.org/timmolter/XChange/builds

Travis CI takes about 15 to 20 minutes IIRC. Snapshots are made by Travis CI.

**Comment by npomfret** [comment]
Sorry, I meant a release (4.2.3-SNAPSHOT ?)

**Comment by timmolter** [comment]
I plan on releasing 4.2.2 on Tuesday (<https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions#what-is-the-release-cycle-for-xchange>), so there will be a 4.2.3-SNAPSHOT then as well.

**Comment by MartianTech** [comment]
@npomfret Were you able to use Coinbase's API to get crypto address and network transaction id for Gdax?

**Pull request merged**
