### PR TITLE
migrated authenticated part to api v2 + some implementations added (ex: get all books)

### PR DESCRIPTION
**Pull request by cymp**
some renaming still needs to be done as there is some BTER references left. Some unit tests have been removed since not used anymore (deserialization), test data updated with gate.io specifications. This has been tested on a basic app: place/cancel orders, get balance, get all order books, get open orders, ...

### CODE REVIEW

**Comment by timmolter** [comment]
@cymp I did the renaming and fixing. Sorry to have not seen this before. Now I think it's too hard to merge, so I'm closing it.

**Comment by cymp** [comment]
My work is after yours, maybe you missed my comment "migrated authenticated part to api v2" ? v1 is not documented on their site and although still works, it returns incomplete information and has high chances of being deprecated very soon. Are you sure you want to close my PR instead of merging it? I planned to rename the last BTER references today, I can still do it if you accept my PR.

**Comment by timmolter** [comment]
Oh, sorry. Can you check these conflicts though? I'm happy to merge it afterwards..

**Comment by cymp** [comment]
Yes, I am on it.

**Comment by cymp** [comment]
Those conflicts are not valid anymore: GateioTickers.java has been deleted, and the two remaining GateioMarketDataServiceRaw and GateioAdapterTest were using it and have been modified. I think you can merge ?

**Comment by timmolter** [comment]
I believe you and I would if I could, but it's not letting me. Is it possible to create a new PR?

**Comment by cymp** [comment]
I am closing this and reopening a new one, as it says that a PR already exists.

**Pull request closed without merging**
