### PR TITLE
[BitFinex] Implemented proper wallets adaptation

### LINKED ISSUE #1535: [Bitfinex] (DEV)  AccountInfo .getWallets() not returns wallet names  like deposit, exchange,..
AccountInfo .getWallets() not returns wallet names  like deposit, exchange,.. 
It does return some info like total balance value usd and how much is used and is free but it doesn't differenciate between  deposit, exchange, margin .anymore.

### PR DESCRIPTION
**Pull request by hurricup**
Wallets are now separated by types

Fixes #1535

### CODE REVIEW

**Comment by hurricup** [comment]
Do not merge!!! Need fixes

**Comment by npomfret** [comment]
can you explain what the change in behaviour for this pr is?

**Comment by hurricup** [comment]
There are 3 different wallets on BitFinex:

- Exchange wallet is used for exchanging funds between our supported currencies.
- Margin wallet is used for trading leveraged short and long positions.
- Funding wallet is used for providing margin funding/financing to other traders.

atm. XChange just sums balances on these and creates one wallet object. But this makes a little sense.
I've implemented 3 wallets with type as id.

**Comment by npomfret** [comment]
@hurricup that sounds good.  thanks

**Pull request merged**
