### PR TITLE
ItBit: Update market data API endpoints.

### PR DESCRIPTION
**Pull request by kmels**
The endpoints for trades and order book have been updated. GetTrades() wraps the response in an object with a count now.

There are sometimes that the API returns 404 of course. Any pointer on how to bind these 404 responses to java classes or exceptions with rescu?..

### CODE REVIEW

**Comment by timmolter** [comment]
@mmazi Do you have a quick answer to his question about 404 responses?

**Comment by mmazi** [comment]
I think this should be resolved in the context of general exception handling within XChange. (I don't think it's a rescu issue.)

I've wanted to propose some general solution for exception handing within XChange for a while, but never got down to do it. I'll try to write something down soon since is don't fully agree with the way this is proposed eg. in #1063. More on this to follow.

**Comment by kmels** [comment]
Don't know much about rescu's proxy, but what if it returned the json data wrapped in an exception when it gets 404 responses (or any 4xx)?

**Comment by mmazi** [comment]
Oh, perhaps I misunderstood the original question.

> Don't know much about rescu's proxy, but what if it returned the json data wrapped in an exception when it gets 404 responses (or any 4xx)?

That's exactly what rescu can do, and it's very easy to implement: just create a Jackson-mapped exception class (preferably by extending `HttpStatusExceptionSupport`) and declare it on the interface method(s). There are many examples of this in XChange, and here's the docs:
https://github.com/mmazi/rescu/wiki/Exception-handling

Don't hesitate to ask if you need further help implementing it.

**Pull request merged**
