### PR TITLE
[cexio] Completing implementation of requestDepositAddress.

### PR DESCRIPTION
**Pull request by bryantharris**
Fleshing out the implementation of requestDepositAddress.

### CODE REVIEW

**Comment by timmolter** [comment]
There's a compile error.

**Comment by bryantharris** [comment]
What is the error, maybe I missed a file when I forked and copied it from the original branch.

**Comment by bryantharris** [comment]
Sorry, the cexio package itself uses the prefix CexIO and sometimes Cexio for class names and it looks like when I was going through the files in an attempt to match pre-existing coding/name conventions I did so without also updating the file name.  Should be fixed.

**Comment by bryantharris** [comment]
@timmolter Created new pull request, you can close this one.

**Pull request closed without merging**
