### PR TITLE
Merged to new snapshot

### PR DESCRIPTION
**Pull request by jclaruelle**
Previous version was based on old version. I merged to new snapshot.

### CODE REVIEW

**Comment by baffo32** [comment]
getOrderBook is returning http status 500?
see AllIntegration test in examples

**Comment by jclaruelle** [comment]
No it should not normally, except if there is some issue on server at this time.

If you look at Unit Test  publicTest in com.xeiam.xchange.cryptofacilities.service.marketdata.FetchIntegration, the below code works correctly:

 

             OrderBook orderBook = marketDataService.getOrderBook(new CurrencyPair(firstContract.getTradeable(), firstContract.getUnit()));

             System.out.println(orderBook);

 

JC

 

De : baffo32 [mailto:notifications@github.com] 
Envoyé : jeudi 10 décembre 2015 04:06
À : timmolter/XChange
Cc : jclaruelle
Objet : Re: [XChange] Merged to new snapshot (#1126)

 

getOrderBook is returning http status 500?
see AllIntegration test in examples

—
Reply to this email directly or view it on GitHub <https://github.com/timmolter/XChange/pull/1126#issuecomment-163471465> .  <https://github.com/notifications/beacon/ANiWW9QLHdncwLqriNy_yV8SrygCwjNMks5pOOOugaJpZM4Gw0B2.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by baffo32** [comment]
ah it was doing that if I used the currencypairs returned by the exchange metadata.  Do you think it would be appropriate to implement remoteInit() to fill that with the contracts available?  Or does cryptofacilities function differently here?

**Comment by jclaruelle** [comment]
I guess it would be possible to what you say, fill the available contracts in a remoteInit() method.

 

JC

 

De : baffo32 [mailto:notifications@github.com] 
Envoyé : jeudi 10 décembre 2015 13:49
À : timmolter/XChange
Cc : jclaruelle
Objet : Re: [XChange] Merged to new snapshot (#1126)

 

ah it was doing that if I used the currencypairs returned by the exchange metadata. Do you think it would be appropriate to implement remoteInit() to fill that with the contracts available? Or does cryptofacilities function differently here?

—
Reply to this email directly or view it on GitHub <https://github.com/timmolter/XChange/pull/1126#issuecomment-163601465> .  <https://github.com/notifications/beacon/ANiWWwabQDnOpZkAZVOm_XQNoBeC5ehOks5pOWwqgaJpZM4Gw0B2.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Pull request merged**
