### PR TITLE
[kraken] various bugfixes

### PR DESCRIPTION
**Pull request by henryxwong**
fix also NPE issue from last PR

### CODE REVIEW

**Comment by timmolter** [comment]
This seems to be the same PR that I reverted a few days ago

**Comment by henryxwong** [comment]
No I fixed the npe issue

**Comment by timmolter** [comment]
Please submit a new PR with only the NPE fix.

**Comment by henryxwong** [comment]
there will be merge conflict if we use the old PR due to massive code re-formatting
so I would suggest we take this one instead of adding a npe fix on top of prev one

**Comment by henryxwong** [comment]
@timmolter 

Also, I've squash my commits on my repo after rebasing with 4.3.4 changes. It is impossible for me to go back in time to make another commit on top of a squashed commit.

Please re-consider this PR when you have time. Or let me know if you prefer a new one. Thanks.

**Comment by timmolter** [comment]
I cannot accept the PR as it is as it contains more changes than just the NPE fix. I prefer a new one.

**Pull request closed without merging**
