### PR TITLE
Huobi refactor

### PR DESCRIPTION
**Pull request by jheusser**
This commit hopefully cleans up the Huobi / BitVc mess a bit. This implementation is now called `xchange-huobi` and by default when instantiating will trade on huobi.com (market data, account, trade). If the flag `use_bitvc` is set then this will use market data from huobi and account/trade data from BitVc. A unit test ensures that future refactors will respect the `use_bitvc` flag logic.

Changes for users:
- package change `com.xeiam.xchange.bitvc.BitVcExchange` -> `com.xeiam.xchange.huobi.HuobiExchange`  

@timmolter

### CODE REVIEW

**Comment by glabmoris** [comment]
Great commit. Please merge ASAP, I have a Huobi/BitVC PR as well, so I'd enjoy having the updated classes (which were in dire need of a refactor).

**Comment by timmolter** [comment]
Sorry for letting this slip through the cracks. @jheusser Can you look into the merging issues?

**Comment by jheusser** [comment]
@timmolter ah didn't notice it failed, looking into it today

**Comment by jheusser** [comment]
@glabmoris if you have any questions/issues with your PR and changes to Huobi, let me know.

**Comment by glabmoris** [comment]
@jheusser Thanks I will. The TradeService didn't seem to be properly selected for huobi users, I am getting error code 67 (private key invalid) when trying to use the TradeService. MarketData is alright, but I think this is related to 

```
  @Override
  public void applySpecification(ExchangeSpecification exchangeSpecification) {

    super.applySpecification(exchangeSpecification);

    pollingMarketDataService = new BitVcMarketDataService(this);
    if (exchangeSpecification.getApiKey() != null) {
      if ((Boolean) exchangeSpecification.getExchangeSpecificParametersItem(USE_HUOBI)) {
        pollingAccountService = new HuobiAccountService(this);
        pollingTradeService = new BitVcTradeService(this); // <--- uh?

      } else {

        pollingAccountService = new BitVcAccountService(this);
        pollingTradeService = new BitVcTradeService(this);
      }
    }
  }
```

I hope your PR cleans that mess :)

**Comment by jheusser** [comment]
@glabmoris this is code from the old snapshot. Huobi will not work properly with it, only BitVc.

**Comment by glabmoris** [comment]
@jheusser Yeah I know. I've built the refactored module, and now I'm getting the following exception message when trying to buy:

Error code: 48

Oddly enough, there's no error mapped to error code 48 in the docs.

**Pull request merged**
