### PR TITLE
Added C-Cex

### PR DESCRIPTION
**Pull request by atlet**
Only public data:
- Order Book
- Trades

### CODE REVIEW

**Comment by timmolter** [comment]
Looks like your versions are wrong.

**Comment by timmolter** [comment]
Could you rename some of the classes' names with LIVECOIN to Livecoin?

**Comment by atlet** [comment]
I will rename, tnx for suggestions.
Which versions are wrong?

**Comment by timmolter** [comment]
i guess there are no versions issue now. CI errors are gone.

**Comment by atlet** [comment]
C-Cex is ok, but I just started Livecoin. I hope will add today Orderbook and trades...

**Pull request merged**
