### PR TITLE
Refactor AccountInfo

### LINKED ISSUE #1039: OkCoin.cn returning several wallets for same currency.
I opened Loan/Lend wallet at okcoin.cn (https://www.okcoin.cn/lend/lends.do)

I think this made some difference on getting wallet list.
I currently get 6 wallets.

xchange-okcoin

First wallet is CNY, and it has "available" string in description.
I get some more wallets with same CNY and "loan" string in description at index 5.

Current API is just returning one wallet by currency string and I can't get normal CNY wallet that has "available" description.

I can call getWallets() and retrieve it manually but why I'm posting issue is that I found description field is deprected.
description field is important to distinguish wallets in okcoin.cn

I'm not familiar with XChange yet and I'm not sure what is better solution. Just want to say description field must not be deprecated in this situation.

### LINKED ISSUE #1059: Question to Balance / Available / Frozen
I write a program to generate statistics for me about a bot I use. 
I check the Exchanges BTer, Poloniex, Cryptsy, Bleutrade and Bittrex.
Now, the first three exchange that I verified have not the correct values in this fields.
Question:
frozen == value that used in trades. Not available for work.
available == value available for work.
balance = frozen + avaliable.
Correct?
Bleutrade/Cryptsy/Poloniex have only available value in balance and available fields.

Sample Pononiex:
Web:
[WDC] Worldcoin 566.62130431 
On orders: 375.56498163 
BTC value: 0.02205658

XChange:
Wallet [currency=WDC, balance=566.62130431, available=566.62130431, frozen=0, description=]

Is this correct? I think no.

### LINKED ISSUE #1065: 300 mBTC Bounty - Clean up `AccountInfo`
figure out best Wallets solution. See:

* <https://github.com/timmolter/XChange/issues/1039>
* <https://github.com/timmolter/XChange/issues/1059>

Propose a good solution, address TODOs, remove deprecated code, refactor all implementations and example code as needed.

### PR DESCRIPTION
**Pull request by baffo32**
- Renamed `Wallet` to `Balance` to leave room for a `Wallet` class having the same meaning as that used in multi-wallet exchange apis
- Split wallet data out from `AccountInfo` into new `Wallet` class with a string id and name
- `AccountInfo` now has multiple `Wallet`s if needed
- Implemented additional fields in `Balance` to provide for variety of balances offered by exchanges
- Removed deprecated methods
- All integration tests pass

- fixes #1039 
- fixes #1059 although it was already some addressed

I did not implement a solution to the bitfinex situation (offers a different wallet for trading, lending, etc).  I think this is a separate issue.  Current XChange only supports trading anyway, so it makes sense to only present that wallet.

I did not implement an interface to query services for only specific wallets.  I think this is better done by the split interface solution discussed in #1101 .

I propose that this fixes #1065 .

### CODE REVIEW

**Comment by timmolter** [comment]
Excellent! 

> I did not implement a solution to the bitfinex situation (offers a different wallet for trading, lending, etc). I think this is a separate issue. Current XChange only supports trading anyway, so it makes sense to only present that wallet.

I'd say just leave it as is because Bitfinex is the only exchange with this feature. People can use the raw API if they need it.

> I did not implement an interface to query services for only specific wallets. I think this is better done by the split interface solution discussed in #1101 .

I guess that's the next issue to tackle then, right?

**Comment by baffo32** [comment]
> > I did not implement an interface to query services for only specific wallets. I think this is better done by the split interface solution discussed in #1101 .
>
> I guess that's the next issue to tackle then, right?

Yup.  I'm working on that at https://github.com/baffo32/XChange/tree/refactor .  It'll be a big job though.

**Comment by mmazi** [comment]
@baffo32 Great job on the balances!

Perhaps another method on `Balance` would be useful: getAvailableForWithdrawal(). I'm guessing it could simply be `{ return available.subtract(borrowed); }`, but I'm not sure whether borrowed funds can be withdrawn. Or perhaps this is exchange-specific?

**Comment by baffo32** [comment]
@mmazi Thanks.  I'm glad to implement that method for you.  I think it makes sense -- even if it's exchange-specific it's the safe default.

**Comment by mmazi** [comment]
Merged. Thanks!

**Pull request merged**
