### PR TITLE
[Binance] Add support for Stop-Limit orders

### LINKED ISSUE #2061: [Binance] Add support for Stop-Limit orders

### PR DESCRIPTION
**Pull request by tdiesler**
resolves #2061

### CODE REVIEW

**Comment by timmolter** [comment]
Should we maybe have separate order objects instead? 

* MarketOrder
* LimitOrder
* StopLossOrder
*StopossLimitOrder

**Comment by tdiesler** [comment]
Your call. IMHO Stop-Limit is a simple enough extension to LimitOrder. Stop-Limit may also conceptually not be a clean extension of Stop-Loss

**Comment by theo1985** [comment]
@timmolter I implemented the StopOrder in #2239.

Stop orders are not only used to exit a position.  They may also be used to enter a position, and as such should be logically separated from LimitOrder (not extended).  This is seen in GDAX, for example.

Maybe we can link a Stop/Limit to an Order by calling: Order.addStopLoss(StopOrder) and/or Order.addTakeProfit(LimitOrder); so as to simulate StopLoss and TakeProfit(StopLossLimit).  

This design would also cover OCO (known as ParentOrders in OkCoin).

**Comment by timmolter** [comment]
I merged #2239, as I liked the implementation better. 

@theo1985 Yeah, the linking of the orders seems like a good idea.

**Pull request closed without merging**
