### PR TITLE
-?

### PR DESCRIPTION
**Pull request by douggie**

### CODE REVIEW

**Comment by timmolter** [comment]
@douggie You'll need to make a PR against the `develop` branch and not the `master` branch.

**Comment by douggie** [comment]
Hi Tim,

Odd, I see the pull request against develop. Also wondered if you and  any
thoughts it I should update com.xeiam.xchange.dto.trade.limitorder to have
a constructor that allows setting of futures contracts, so
com.xeiam.xchange.okcoin.service.polling.OkCoinFuturesTradeService can
support this:

Might also require moving the futuresContract enum to core.

    @Override

    public String placeLimitOrder(LimitOrder limitOrder) throws IOException
{

        FuturesContract futuresContract = FuturesContract.ThisWeek;

        //TODO: update limit order to support setting of futures contract

        long orderId =
futuresTrade(OkCoinAdapters.adaptSymbol(limitOrder.getCurrencyPair()),
limitOrder.getType() == OrderType.BID ? "1" : "2",

                limitOrder.getLimitPrice().toPlainString(),
limitOrder.getTradableAmount().toPlainString(),
limitOrder.getFuturesContract(), 0).getOrderId();

        return String.valueOf(orderId);

    }




Support trade methods on okcoin futures #912
 Open
douggie <https://github.com/douggie> wants to merge 1 commit into timmolter:
develop from douggie:develop
+276 −241 
 Conversation 1 <https://github.com/timmolter/XChange/pull/912>  Commits 1
<https://github.com/timmolter/XChange/pull/912/commits>  Files changed 4
<https://github.com/timmolter/XChange/pull/912/files>

**Comment by timmolter** [comment]
@douggie see screenshot. It says timmolter:master

screen shot 2015-03-30 at 11 04 06 am

**Comment by douggie** [comment]
Hi tim,

Think hub did something odd. Belive to correct pr is 912 just reject 913

**Comment by timmolter** [comment]
alright. Thanks.

**Comment by douggie** [comment]
Hi tim, any thoughts on if should change limit orders to have a futures
contract field rather than having a okcoin specfic limit order class that
extends the core limit order class. Might need to also add position effect
field to indicate if open or closing.

**Comment by timmolter** [comment]
@douggie Can you please point me to the OKCoin class that extends LimitOrder so I can take a look? In any case that should be a separate issue and PR. Let's get that existing PR from you merged first, but I'm still waiting to see if you can format the code so I can review the PR more easily.

**Comment by douggie** [comment]
Ah tim! Cancel the pr if you like!! My formatter dissapeared with a new
eclipse install.

There is no okcoin specific limit order class yet. But i can create one
that entends core limit order, but then a developer needs to explicitly
reference that clsss. Or can add new constructor to the core limit order
class. Happy to do eitger. Just wondered if ypu had a preference.

Let me get the formatter back reformat and do a new pr.

Sorry tim!

**Comment by timmolter** [comment]
No rush, no worries. And you don't need a new PR. Just format and push once again to your fork and the existing PR #912 will automatically update. 

Regarding the other issue, I'd prefer if you could open another PR (after the first one is merged) so I and others can look at exactly what you're proposing. I'd say add new constructor to the core limit order
class as you are proposing and we'll see what it looks like.

**Comment by douggie** [comment]
Great will do it seperatly. Was just looking to get ypur prefered approach.

**Comment by douggie** [comment]
Formatting resolved.

**Pull request closed without merging**
